# Generated by Django 5.2.7 on 2025-10-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='important',
            field=models.BooleanField(default=False),
        ),
    ]
