# Generated by Django 5.2.7 on 2025-10-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_article_category_remove_article_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='context'),
        ),
    ]
